# Generated by Django 2.2.24 on 2026-02-13 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('post', models.CharField(max_length=300)),
                ('pin', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('pic', models.CharField(max_length=300)),
                ('latitude', models.CharField(max_length=300)),
                ('longitude', models.CharField(max_length=300)),
                ('proof', models.CharField(max_length=300)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('post', models.CharField(max_length=300)),
                ('pin', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('bio', models.CharField(max_length=300)),
                ('proof', models.CharField(max_length=300)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='offered_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COLLEGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.college')),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.course')),
            ],
        ),
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=300)),
                ('qualification', models.CharField(max_length=300)),
                ('skills', models.CharField(max_length=300)),
                ('experience', models.CharField(max_length=300)),
                ('apply_form', models.CharField(max_length=300)),
                ('apply_to', models.CharField(max_length=300)),
                ('COMPANY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.company')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('semester', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=300)),
                ('credit', models.CharField(max_length=300)),
                ('max_mark', models.CharField(max_length=300)),
                ('COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.course')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=300)),
                ('post', models.CharField(max_length=300)),
                ('pin', models.CharField(max_length=300)),
                ('date_of_birth', models.CharField(max_length=300)),
                ('joining_year', models.CharField(max_length=300)),
                ('roll_number', models.CharField(max_length=300)),
                ('image', models.CharField(default='', max_length=300)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('OFFERED_LIST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.offered_list')),
            ],
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_mark', models.CharField(max_length=300)),
                ('external_mark', models.CharField(max_length=300)),
                ('result', models.CharField(max_length=300)),
                ('total', models.CharField(max_length=300)),
                ('grade_point', models.CharField(max_length=300)),
                ('grade', models.CharField(max_length=300)),
                ('credit_point', models.CharField(max_length=300)),
                ('public_status', models.CharField(max_length=300)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.student')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.subject')),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=300)),
                ('c_date', models.CharField(max_length=300)),
                ('replay', models.CharField(max_length=300)),
                ('r_date', models.CharField(max_length=300)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.student')),
            ],
        ),
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=300)),
                ('issue_date', models.CharField(max_length=300)),
                ('file', models.CharField(max_length=300)),
                ('qrcode', models.CharField(max_length=300)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.student')),
            ],
        ),
        migrations.CreateModel(
            name='applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_to', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('interview_date', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.student')),
                ('VACANCY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.vacancy')),
            ],
        ),
    ]
